apiVersion: v1
kind: ConfigMap
metadata:
  name: granite-chat-template
  namespace: model-deploy-lab
data:
  granite.jinja: |
    {% for message in messages %}
    <|start_of_role|>{{ message['role'] }}<|end_of_role|>{{ message['content'] }}<|end_of_text|>
    {% endfor %}
    {% if add_generation_prompt %}
    <|start_of_role|>assistant<|end_of_role|>
    {% endif %}