apiVersion: v1
kind: Secret
metadata:
  name: minio-data-connection
  namespace: model-deploy-lab
  labels:
    opendatahub.io/dashboard: "true"
    networking.kserve.io/is-shared: "true"
  annotations:
    # UPDATED: Using full FQDN + Port 9000
    serving.kserve.io/s3-endpoint: "http://minio-service.model-deploy-lab.svc.cluster.local:9000"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-use-https: "0"
    serving.kserve.io/s3-verifyssl: "0"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  # UPDATED: Matching the annotation
  AWS_S3_ENDPOINT: http://minio-service.model-deploy-lab.svc.cluster.local:9000
  AWS_DEFAULT_REGION: us-east-1